COMMON_SRCS = ./Common/Changes.cpp \
	      ./Common/CommandLine.cpp \
	      ./Common/FileSystem.cpp \
	      ./Common/Pipe.cpp \
	      ./Common/Utility.cpp \
	      ./Common/VersionedAsset.cpp \
	      ./Common/Status.cpp \
	      ./Common/Connection.cpp \
	      ./Common/Command.cpp \
		  ./Common/Log.cpp \
		  ./Common/POpen.cpp

COMMON_INCLS = ./Common/Changes.h \
	       ./Common/CommandLine.h \
	       ./Common/FileSystem.h \
	       ./Common/Pipe.h \
	       ./Common/Utility.h \
	       ./Common/VersionedAsset.h \
	       ./Common/Status.h \
		   ./Common/Connection.h \
	       ./Common/Command.h \
		   ./Common/Dispatch.h \
		   ./Common/Log.h \
		   ./Common/POpen.h

TESTSERVER_SRCS = ./Test/Source/ExternalProcess_Posix.cpp \
				./Test/Source/TestServer.cpp 
TESTSERVER_INCLS = ./Test/Source/ExternalProcess.h
TESTSERVER_INCLUDE = -I./Common

P4PLUGIN_SRCS = ./P4Plugin/Source/P4Plugin_Posix.cpp \
		./P4Plugin/Source/P4AddCommand.cpp \
		./P4Plugin/Source/P4ChangeDescriptionCommand.cpp \
		./P4Plugin/Source/P4ChangeMoveCommand.cpp \
		./P4Plugin/Source/P4ChangesCommand.cpp \
		./P4Plugin/Source/P4ChangeStatusCommand.cpp \
		./P4Plugin/Source/P4CheckoutCommand.cpp \
		./P4Plugin/Source/P4Command.cpp \
		./P4Plugin/Source/P4ConfigCommand.cpp \
		./P4Plugin/Source/P4DeleteChangesCommand.cpp \
		./P4Plugin/Source/P4DeleteCommand.cpp \
		./P4Plugin/Source/P4DownloadCommand.cpp \
		./P4Plugin/Source/P4ExitCommand.cpp \
		./P4Plugin/Source/P4FileSetBaseCommand.cpp \
		./P4Plugin/Source/P4GetLatestCommand.cpp \
		./P4Plugin/Source/P4IncomingChangeAssetsCommand.cpp \
		./P4Plugin/Source/P4IncomingCommand.cpp \
		./P4Plugin/Source/P4LockCommand.cpp \
		./P4Plugin/Source/P4LoginCommand.cpp \
		./P4Plugin/Source/P4LogoutCommand.cpp \
		./P4Plugin/Source/P4MoveCommand.cpp \
		./P4Plugin/Source/P4QueryConfigParametersCommand.cpp \
		./P4Plugin/Source/P4ResolveCommand.cpp \
		./P4Plugin/Source/P4RevertChangesCommand.cpp \
		./P4Plugin/Source/P4RevertCommand.cpp \
		./P4Plugin/Source/P4SpecCommand.cpp \
		./P4Plugin/Source/P4StatusBaseCommand.cpp \
		./P4Plugin/Source/P4StatusCommand.cpp \
		./P4Plugin/Source/P4SubmitCommand.cpp \
		./P4Plugin/Source/P4FileModeCommand.cpp \
		./P4Plugin/Source/P4Task.cpp \
		./P4Plugin/Source/P4UnlockCommand.cpp \
		./P4Plugin/Source/P4InfoCommand.cpp \
		./P4Plugin/Source/P4StreamsCommand.cpp \
		./P4Plugin/Source/P4Utility.cpp

P4PLUGIN_INCLS = ./P4Plugin/Source/P4Command.h \
		 ./P4Plugin/Source/P4FileSetBaseCommand.h \
		 ./P4Plugin/Source/P4StatusBaseCommand.h \
		 ./P4Plugin/Source/P4StatusCommand.h \
		 ./P4Plugin/Source/P4Task.h \
		 ./P4Plugin/Source/P4Info.h \
		 ./P4Plugin/Source/P4Stream.h \
		 ./P4Plugin/Source/P4Utility.h

P4PLUGIN_LINK = -lclient -lrpc -lsupp -lssl -lcrypto
P4PLUGIN_INCLUDE = -I./Common -I./P4Plugin/Source/r17.2/include/p4 -I./P4Plugin/Source
